version: '3'

services:
    app:
        container_name: reactapp
        image: reactapp:latest
        build: .
        environment:
            - NODE_ENV=production
        ports:
            - 8080:5000
        restart: always
